apiVersion: v1
kind: Service
metadata:
  name: agentnexus
  labels:
    app: agentnexus
spec:
  type: ClusterIP
  selector:
    app: agentnexus
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
