"""Cine pipeline — Jinja2 static HTML report generator.

B10: media src uses os.path.relpath from report_dir to source file, with POSIX separators.
"""
from __future__ import annotations

import os
import tempfile
from pathlib import Path, PurePosixPath
from typing import List, Optional

from .schemas import CutCandidate, EvidenceRecord, SourceMediaRecord, SourceShot, ValidationResult

try:
    from jinja2 import Environment, BaseLoader
    _JINJA2_OK = True
except ImportError:
    _JINJA2_OK = False


_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Cine Pipeline Report — {{ source_name }}</title>
<style>
body { font-family: sans-serif; margin: 2em; background: #111; color: #eee; }
h1,h2 { color: #f90; }
table { border-collapse: collapse; width: 100%; margin-bottom: 2em; }
th { background: #333; padding: 6px 10px; text-align: left; }
td { border-bottom: 1px solid #333; padding: 5px 10px; }
tr:hover { background: #222; }
video { max-width: 100%; }
.badge-candidate { color: #0af; }
.badge-unavailable { color: #fa0; }
.pass { color: #0f0; }
.fail { color: #f44; }
img { max-height: 120px; margin: 2px; border: 1px solid #444; }
</style>
</head>
<body>
<h1>Cine Pipeline Report</h1>
<p><strong>Source:</strong> {{ source_name }}</p>
<p><strong>Duration:</strong> {{ duration_s }}</p>
<p><strong>Revision:</strong> {{ revision_id }}</p>
<p><strong>Validation:</strong>
  {% if validation_passed %}
  <span class="pass">PASSED</span>
  {% else %}
  <span class="fail">FAILED ({{ issue_count }} error(s))</span>
  {% endif %}
</p>

<h2>Video Player</h2>
<!-- B10: media_rel_path is os.path.relpath from report_dir to source; POSIX separators. -->
<!-- data-source-abs provided for local server/player tools that need the absolute path. -->
<video controls data-source-abs="{{ media_abs_path }}">
  <source src="{{ media_rel_path }}" type="video/mp4">
  Media preview requires the source file to be served from the same location as this report.
  Absolute path: {{ media_abs_path }}
</video>

<h2>Cut Candidates ({{ candidate_count }})</h2>
<table>
  <tr>
    <th>#</th><th>PTS</th><th>Time (s)</th><th>Detector</th><th>Score</th>
    <th>Status</th><th>Evidence</th>
  </tr>
  {% for row in candidate_rows %}
  <tr>
    <td>{{ loop.index }}</td>
    <td>{{ row.pts }}</td>
    <td>{{ "%.3f"|format(row.pts_seconds) }}</td>
    <td>{{ row.detector }}</td>
    <td>{{ row.score if row.score is not none else '—' }}</td>
    <td class="badge-{{ row.status }}">{{ row.status }}</td>
    <td>
      {% for ev in row.evidence_items %}
        {% if ev.kind.startswith('frame') and ev.exists %}
          <img src="{{ ev.rel_path }}" title="{{ ev.kind }}" alt="{{ ev.kind }}">
        {% elif ev.kind == 'clip_boundary' and ev.exists %}
          <a href="{{ ev.rel_path }}">[clip]</a>
        {% endif %}
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
</table>

{% if shots %}
<h2>Source Shots ({{ shots|length }})</h2>
<table>
  <tr><th>#</th><th>Shot ID</th><th>In PTS</th><th>Out PTS</th><th>In (s)</th><th>Out (s)</th></tr>
  {% for sh in shots %}
  <tr>
    <td>{{ loop.index }}</td>
    <td>{{ sh.shot_id[:8] }}</td>
    <td>{{ sh.in_pts }}</td>
    <td>{{ sh.out_pts }}</td>
    <td>{{ "%.3f"|format(sh.in_seconds) }}</td>
    <td>{{ "%.3f"|format(sh.out_seconds) }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% if validation_issues %}
<h2>Validation Issues</h2>
<table>
  <tr><th>Severity</th><th>Code</th><th>Message</th></tr>
  {% for issue in validation_issues %}
  <tr>
    <td>{{ issue.severity }}</td>
    <td>{{ issue.code }}</td>
    <td>{{ issue.message }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

<p style="color:#555; font-size:0.8em">Generated by Cine Pipeline C0+C1. All cuts remain <em>candidate</em> status pending human review.</p>
</body>
</html>
"""


def render_report(
    revision_dir: Path,
    source: SourceMediaRecord,
    revision_id: str,
    candidates: List[CutCandidate],
    shots: List[SourceShot],
    evidence: List[EvidenceRecord],
    validation: Optional[ValidationResult],
    *,
    report_filename: str = "report.html",
) -> Path:
    """
    Generate a standalone static HTML report and write it to revision_dir/report/.
    Returns path to written file.
    Raises RuntimeError if Jinja2 is not available.

    B10: <source src> uses os.path.relpath(media_path, report_dir) with POSIX separators,
    so the browser can load the file when opened from the report directory.
    """
    if not _JINJA2_OK:
        raise RuntimeError("Jinja2 is not installed; cannot render report")

    report_dir = revision_dir / "report"
    report_dir.mkdir(parents=True, exist_ok=True)
    out_path = report_dir / report_filename

    # Build evidence lookup by candidate_id
    ev_by_candidate: dict = {}
    for ev in evidence:
        if ev.candidate_id:
            ev_by_candidate.setdefault(ev.candidate_id, []).append(ev)

    candidate_rows = []
    for c in candidates:
        ev_items = []
        for ev in ev_by_candidate.get(c.candidate_id, []):
            if ev.relative_path is None:
                continue
            ev_path = revision_dir / ev.relative_path
            ev_items.append({
                "kind": ev.kind,
                "rel_path": str(Path("..") / ev.relative_path),
                "exists": ev_path.exists(),
            })
        candidate_rows.append({
            "pts": c.pts,
            "pts_seconds": c.pts_seconds,
            "detector": c.detector,
            "score": c.score,
            "status": c.status.value,
            "evidence_items": ev_items,
        })

    shot_rows = []
    for sh in shots:
        shot_rows.append({
            "shot_id": sh.shot_id,
            "in_pts": sh.interval.in_pts,
            "out_pts": sh.interval.out_pts,
            "in_seconds": sh.interval.in_seconds,
            "out_seconds": sh.interval.out_seconds,
        })

    media_path = Path(source.path)
    # B10: compute relative path from report_dir to media file, POSIX separators
    try:
        rel = os.path.relpath(str(media_path), str(report_dir))
        media_rel_path = Path(rel).as_posix()
    except ValueError:
        # on Windows, relpath can fail across drives — fall back to filename only
        media_rel_path = media_path.name

    media_abs_path = str(media_path.resolve())
    duration_s = f"{source.duration_seconds:.3f}s" if source.duration_seconds else "unknown"

    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(_TEMPLATE)
    html = tmpl.render(
        source_name=media_path.name,
        duration_s=duration_s,
        revision_id=revision_id,
        media_rel_path=media_rel_path,
        media_abs_path=media_abs_path,
        candidate_count=len(candidates),
        candidate_rows=candidate_rows,
        shots=shot_rows,
        validation_passed=validation.passed if validation else True,
        issue_count=sum(1 for i in (validation.issues if validation else []) if i.severity == "error"),
        validation_issues=[i.model_dump() for i in (validation.issues if validation else [])],
    )

    tmp_fd, tmp_path = tempfile.mkstemp(dir=str(report_dir), suffix=".tmp.html")
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as fh:
            fh.write(html)
        os.replace(tmp_path, str(out_path))
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise

    return out_path
